---
title: "EGC5310 — Semana 03"
subtitle: "Operações sobre dados: inserir, remover, ordenar e medir"
author: "Prof. Vinicius Ramos"
execute:
  echo: true
---

<div class="not-slide">

[![Abrir no Google Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/professorviniciusramos/EGC5310-EstruturasDados/blob/main/Semana03/EGC5310-EstruturasDados-S03-99-Aula-Mestre.ipynb)

</div>

## EGC5310 {.title-slide-custom}

<img src="../assets/Logo_03.png" class="course-logo" alt="Logo Ciência de Dados UFSC">

<div class="course-name">ESTRUTURAS DE DADOS</div>
<div class="week-label">SEMANA 03</div>
<div class="subtitle-custom">Operações sobre dados: inserir, remover, ordenar e medir</div>

## O que realmente acontece quando <span class="gold">modificamos</span> os dados? {.question-slide}

<div class="fragment small-note">Inserir · remover · ordenar · transformar · medir</div>

## De onde estamos vindo?

<div class="question-list">
  <div class="fragment"><strong>S01:</strong> uma solução correta pode deixar de ser adequada quando os dados crescem.</div>
  <div class="fragment"><strong>S02:</strong> a representação depende do que queremos fazer.</div>
  <div class="fragment gold-text"><strong>S03:</strong> quanto trabalho escondem as operações que realizamos?</div>
</div>

## O Sistema Acadêmico não apenas consulta

<div class="question-list">
  <div class="fragment">recebe novas matrículas;</div>
  <div class="fragment">cancela matrículas;</div>
  <div class="fragment">atualiza notas;</div>
  <div class="fragment">incorpora lotes;</div>
  <div class="fragment">produz rankings;</div>
  <div class="fragment">troca dados com outros sistemas.</div>
</div>

::: {.fragment .prompt-gold}
**Essas operações têm o mesmo custo?**
:::

## Uma linha aparentemente simples {.question-slide}

```python
alunos.append(novo_aluno)
```

<div class="question-list">
  <div class="fragment">O que essa linha faz?</div>
  <div class="fragment">Quanto trabalho existe nela?</div>
  <div class="fragment gold-text">Esse trabalho depende do tamanho de <code>alunos</code>?</div>
</div>

## Primeiro: uma lista tem posições

```text
índice      0       1       2       3
         ┌───────┬───────┬───────┬───────┐
lista →  │ Ana   │ Bruno │ Carla │ Diego │
         └───────┴───────┴───────┴───────┘
```

::: {.fragment .question-big}
Para obter `alunos[2]`, precisamos visitar Ana e Bruno?
:::

In [1]:
alunos = [
    {"matricula": 101, "nome": "Ana"},
    {"matricula": 102, "nome": "Bruno"},
    {"matricula": 103, "nome": "Carla"},
    {"matricula": 104, "nome": "Diego"},
]
alunos[2]

{'matricula': 103, 'nome': 'Carla'}

## Acesso por posição {.concept-slide}

<div class="concept-definition">`lista[i]` → `O(1)`</div>

<div class="fragment small-note">
Conhecida a posição, o trabalho não cresce proporcionalmente ao número de elementos da lista.
</div>

## Inserir no final

```text
tamanho = 3
capacidade = 5

[A][B][C][ ][ ]
```

<div class="fragment small-note">Uma lista dinâmica pode reservar mais espaço do que utiliza naquele instante.</div>

::: {.fragment .prompt-gold}
Se existe espaço, adicionar ao final é muito barato.
:::

In [2]:
novo_aluno = {"matricula": 105, "nome": "Eva"}
alunos.append(novo_aluno)
alunos

[{'matricula': 101, 'nome': 'Ana'},
 {'matricula': 102, 'nome': 'Bruno'},
 {'matricula': 103, 'nome': 'Carla'},
 {'matricula': 104, 'nome': 'Diego'},
 {'matricula': 105, 'nome': 'Eva'}]

## Mas e quando o espaço termina?

```text
[A][B][C][D]
```

Chega `E`.

<div class="question-list">
  <div class="fragment">obter uma região maior;</div>
  <div class="fragment">transferir referências existentes;</div>
  <div class="fragment">inserir o novo elemento.</div>
</div>

::: {.fragment .question-big}
Todo `append()` individual realiza exatamente o mesmo trabalho?
:::

## Um termo para guardar {.concept-slide}

<div class="concept-definition">`append()` → `O(1)` <span class="gold">amortizado</span></div>

<div class="fragment small-note">
A maioria das inserções é barata. Algumas, ocasionalmente, precisam crescer a estrutura.
</div>

::: {.fragment .prompt-gold}
Analisamos o custo ao longo de uma **sequência** de operações.
:::

## E se inserirmos no início?

```python
alunos.insert(0, novo_aluno)
```

```text
antes
[A][B][C][D]

        deslocamentos →
[ ][A][B][C][D]

depois
[X][A][B][C][D]
```

In [3]:
exemplo = ["A", "B", "C", "D"]
exemplo.insert(0, "X")
exemplo

['X', 'A', 'B', 'C', 'D']

## A posição mudou o trabalho {.concept-slide}

<div class="concept-definition">`insert(0, x)` → `O(n)`</div>

::: {.fragment .question-big}
Se a lista tiver um milhão de elementos, quantas referências podem precisar ser deslocadas?
:::

## Uma linha de código ≠ uma quantidade de trabalho {.question-slide}

```python
alunos.append(x)
```

```python
alunos.insert(0, x)
```

<div class="fragment prompt-gold">
As duas ocupam uma linha. Os mecanismos são diferentes.
</div>

## E para remover?

:::: {.columns}
::: {.column width="48%"}
### Final
```python
lista.pop()
```
:::
::: {.column width="48%"}
### Início
```python
lista.pop(0)
```
:::
::::

::: {.fragment .question-big}
Qual delas pode exigir deslocamentos?
:::

In [4]:
lista = list(range(10))
ultimo = lista.pop()
primeiro = lista.pop(0)
print("removido do final:", ultimo)
print("removido do início:", primeiro)
print("lista restante:", lista)

removido do final: 9
removido do início: 0
lista restante: [1, 2, 3, 4, 5, 6, 7, 8]

## O que já conseguimos explicar?

| Operação | Comportamento | Mecanismo |
|---|---:|---|
| `lista[i]` | `O(1)` | acesso por posição |
| `append(x)` | `O(1)` amortizado | final + crescimento ocasional |
| `insert(0,x)` | `O(n)` | deslocamento |
| `pop()` | `O(1)` | final |
| `pop(0)` | `O(n)` | deslocamento |

## AGORA É COM VOCÊ {.question-slide}

::: {.prompt-gold}
### Notebook Estudante — Atividade 1

**Preveja antes de executar.**

Compare `append`, `insert(0, ...)`, `pop()` e `pop(0)` para coleções crescentes.
:::

[**Abrir Notebook Estudante**](EGC5310-EstruturasDados-S03-04-Estudante.ipynb)

<div class="small-note">Registre a hipótese antes da medição.</div>

## Agora o problema tem duas operações

Chega um novo estudante e precisamos manter um **ranking por nota**.

```text
inserir
   ↓
ordenar
```

::: {.fragment .question-big}
O custo do processo é apenas o custo da inserção?
:::

In [5]:
ranking = [
    {"nome": "Ana", "nota": 9.5},
    {"nome": "Bruno", "nota": 8.7},
    {"nome": "Carla", "nota": 8.2},
]
novo_aluno = {"nome": "Diego", "nota": 9.1}
ranking.append(novo_aluno)
ranking

[{'nome': 'Ana', 'nota': 9.5},
 {'nome': 'Bruno', 'nota': 8.7},
 {'nome': 'Carla', 'nota': 8.2},
 {'nome': 'Diego', 'nota': 9.1}]

## Ordenar também é trabalho

```text
dados desordenados
       ↓
algoritmo de ordenação
       ↓
dados ordenados
```

<div class="fragment small-note">
Não vamos estudar algoritmos de ordenação nesta semana.
</div>

::: {.fragment .prompt-gold}
Algoritmos eficientes de ordenação costumam aparecer na ordem de `O(n log n)`.
:::

## Como informar o critério de ordenação?

Primeiro, uma função comum:

```python
def obter_nota(aluno):
    return aluno["nota"]
```

Depois:

```python
ranking.sort(
    key=obter_nota,
    reverse=True
)
```

<div class="fragment small-note"><code>key=</code> informa qual valor deve orientar a ordenação.</div>

In [6]:
def obter_nota(aluno):
    return aluno["nota"]

ranking.sort(key=obter_nota, reverse=True)
ranking

[{'nome': 'Ana', 'nota': 9.5},
 {'nome': 'Diego', 'nota': 9.1},
 {'nome': 'Bruno', 'nota': 8.7},
 {'nome': 'Carla', 'nota': 8.2}]

## Uma pequena função sem nome

```python
def obter_nota(aluno):
    return aluno["nota"]
```

pode ser escrita como:

```python
lambda aluno: aluno["nota"]
```

```text
lambda aluno: aluno["nota"]
       ↑             ↑
    entrada        saída
```

::: {.fragment .prompt-gold}
`lambda` não muda a ideia: recebe um aluno e devolve sua nota.
:::

In [7]:
ranking.sort(
    key=lambda aluno: aluno["nota"],
    reverse=True
)
ranking

[{'nome': 'Ana', 'nota': 9.5},
 {'nome': 'Diego', 'nota': 9.1},
 {'nome': 'Bruno', 'nota': 8.7},
 {'nome': 'Carla', 'nota': 8.2}]

## Duas estratégias corretas

:::: {.columns}
::: {.column width="48%"}
### A — ordenar sempre
```python
for aluno in novos_alunos:
    ranking.append(aluno)
    ranking.sort(
        key=lambda x: x["nota"],
        reverse=True
    )
```
:::
::: {.column width="48%"}
### B — ordenar uma vez
```python
for aluno in novos_alunos:
    ranking.append(aluno)

ranking.sort(
    key=lambda x: x["nota"],
    reverse=True
)
```
:::
::::

::: {.fragment .question-big}
Mesmo resultado final significa mesmo trabalho?
:::

## Uma nova regra {.concept-slide}

<div class="concept-definition">
**ESTRUTURA + OPERAÇÃO + SEQUÊNCIA**
</div>

<div class="fragment small-note">
O desempenho depende também de quantas vezes e em que ordem realizamos as operações.
</div>

## Benchmark da Semana 03

Vamos comparar:

<div class="question-list">
  <div class="fragment"><code>append()</code> × <code>insert(0, ...)</code>;</div>
  <div class="fragment"><code>pop()</code> × <code>pop(0)</code>;</div>
  <div class="fragment gold-text">DataFrame registro a registro × construção em lote.</div>
</div>

## Antes de medir

<div class="question-list">
  <div class="fragment">variar `n`;</div>
  <div class="fragment">repetir medições;</div>
  <div class="fragment">manter condições comparáveis;</div>
  <div class="fragment">registrar resultados;</div>
  <div class="fragment">observar tendência.</div>
</div>

::: {.fragment .prompt-gold}
**Big-O descreve crescimento. O cronômetro mede uma execução concreta.**
:::

## AGORA É COM VOCÊ {.question-slide}

::: {.prompt-gold}
### Notebook Estudante — Atividade 2

Formule hipóteses e execute o benchmark de inserção e remoção.
:::

[**Abrir Notebook Estudante**](EGC5310-EstruturasDados-S03-04-Estudante.ipynb)

<div class="small-note">Pergunta principal: **como a diferença muda quando `n` cresce?**</div>

## “Professor, eu usaria um <span class="gold">DataFrame</span>” {.question-slide}

<div class="fragment question-big">Por que todo mundo pensa em DataFrame em Ciência de Dados?</div>

In [8]:
import pandas as pd

dados = [
    {"nome": "Ana", "curso": "CD", "nota": 8.5},
    {"nome": "Bruno", "curso": "CC", "nota": 7.2},
    {"nome": "Carla", "curso": "CD", "nota": 9.1},
]

df = pd.DataFrame(dados)
df

    nome curso  nota
0    Ana    CD   8.5
1  Bruno    CC   7.2
2  Carla    CD   9.1

## Uma abstração orientada a dados tabulares

```text
             variáveis
          ↓       ↓       ↓
       nome     curso    nota
      ┌────────┬───────┬──────┐
linha │ Ana    │ CD    │ 8.5  │
linha │ Bruno  │ CC    │ 7.2  │
linha │ Carla  │ CD    │ 9.1  │
      └────────┴───────┴──────┘
```

<div class="fragment prompt-gold">As operações se aproximam da linguagem da análise de dados.</div>

In [9]:
print("média:", df["nota"].mean())
print("\naprovados:")
display(df[df["nota"] >= 7])
print("\nmédia por curso:")
display(df.groupby("curso")["nota"].mean())

média: 8.266666666666666

aprovados:

    nome curso  nota
0    Ana    CD   8.5
1  Bruno    CC   7.2
2  Carla    CD   9.1

média por curso:

curso
CC    7.2
CD    8.8
Name: nota, dtype: float64

## Por isso DataFrame aparece tanto

```python
df["nota"].mean()
df[df["nota"] >= 7]
df.groupby("curso")["nota"].mean()
df.sort_values("nota")
```

::: {.fragment .prompt-gold}
Filtrar, agregar, agrupar e operar sobre colunas fazem parte diretamente da abstração.
:::

## Mas cuidado: DataFrame não é “Big-O melhor”

:::: {.columns}
::: {.column width="48%"}
### Lista
```python
for aluno in alunos:
    aluno["nota"] += 1
```
:::
::: {.column width="48%"}
### DataFrame
```python
df["nota"] += 1
```
:::
::::

<div class="fragment concept-definition">Ambos podem ser `O(n)`.</div>

## Se ambos são `O(n)`, por que os tempos diferem? {.question-slide}

```text
Lista Python      T(n) ≈ a · n
DataFrame         T(n) ≈ b · n
```

<div class="question-list">
  <div class="fragment">overhead do interpretador;</div>
  <div class="fragment">representação de memória;</div>
  <div class="fragment">código compilado;</div>
  <div class="fragment gold-text">vetorização e processamento em lote.</div>
</div>

## Mesma classe ≠ mesmo tempo {.concept-slide}

<div class="concept-definition">Big-O descreve a **taxa de crescimento**.</div>

<div class="fragment small-note">
Constantes, implementação, hardware e representação continuam importando no mundo real.
</div>

## DataFrame é sempre melhor? {.question-slide}

<div class="fragment prompt-gold">Não.</div>

<div class="fragment small-note">
Uma `list` foi projetada para crescer dinamicamente de maneira muito natural.
</div>

```python
alunos.append(novo_aluno)
```

In [10]:
novo_aluno = {"nome": "Diego", "curso": "CD", "nota": 8.9}
novo_df = pd.DataFrame([novo_aluno])
df2 = pd.concat([df, novo_df], ignore_index=True)
df2

    nome curso  nota
0    Ana    CD   8.5
1  Bruno    CC   7.2
2  Carla    CD   9.1
3  Diego    CD   8.9

## E se fizermos isso milhares de vezes?

```python
for aluno in novos_alunos:
    novo_df = pd.DataFrame([aluno])
    df = pd.concat(
        [df, novo_df],
        ignore_index=True
    )
```

::: {.fragment .question-big}
Que estrutura estamos reconstruindo repetidamente?
:::

## Operar em lote muda a estratégia

```python
novos_df = pd.DataFrame(novos_alunos)

df = pd.concat(
    [df, novos_df],
    ignore_index=True
)
```

::: {.fragment .prompt-gold}
DataFrames são especialmente fortes quando operamos sobre **conjuntos de dados**.
:::

## De onde pode surgir `O(n²)`?

Se cada concatenação lida com uma estrutura maior:

```text
1 + 2 + 3 + ... + n
```

<div class="fragment concept-definition">crescimento acumulado → `O(n²)`</div>

<div class="fragment small-note">
Um comportamento quadrático pode surgir de uma decisão plausível de programação.
</div>

## AGORA É COM VOCÊ {.question-slide}

::: {.prompt-gold}
### Notebook Estudante — Atividade 3

Compare construção de DataFrame:

**registro a registro × em lote**
:::

[**Abrir Notebook Estudante**](EGC5310-EstruturasDados-S03-04-Estudante.ipynb)

## “E JSON?” {.question-slide}

```json
[
  {"matricula": 101, "nome": "Ana"},
  {"matricula": 102, "nome": "Bruno"}
]
```

::: {.fragment .question-big}
Qual é o Big-O do JSON?
:::

## A pergunta está incompleta

<div class="concept-definition">JSON é um formato de **representação e intercâmbio**.</div>

<div class="fragment small-note">
Ele não ocupa exatamente o mesmo papel que uma `list` ou um `DataFrame` em memória.
</div>

In [11]:
import json

texto_json = '''
[
  {"matricula": 101, "nome": "Ana"},
  {"matricula": 102, "nome": "Bruno"}
]
'''

dados_json = json.loads(texto_json)

print(type(dados_json))
print(type(dados_json[0]))
print(dados_json)

<class 'list'>
<class 'dict'>
[{'matricula': 101, 'nome': 'Ana'}, {'matricula': 102, 'nome': 'Bruno'}]

## Depois do parsing...

```text
JSON
 ↓
json.loads(...)
 ↓
list
 └── dict
      ├── str
      ├── int
      └── ...
```

::: {.fragment .prompt-gold}
As operações de manipulação passam a ocorrer sobre estruturas em memória.
:::

## O trabalho escondido no JSON

```text
arquivo / mensagem JSON
          ↓
        leitura
          ↓
        parsing
          ↓
  estruturas em memória
          ↓
      manipulação
          ↓
     serialização
          ↓
        escrita
```

<div class="fragment small-note">
Para um documento de tamanho `m`, o parsing completo pode ser modelado introdutoriamente como aproximadamente `O(m)`.
</div>

## Um pipeline real pode usar os três

```text
API
 ↓
JSON
 ↓ desserialização
list / dict
 ↓ manipulação incremental
DataFrame
 ↓ análise tabular
JSON
 ↓ serialização
outro sistema
```

::: {.fragment .prompt-gold}
Não existe um vencedor absoluto.
:::

## Então quando usar cada um?

| Necessidade | `list` | `DataFrame` | JSON |
|---|---|---|---|
| crescer registro a registro | muito natural | geralmente não ideal | não é a finalidade |
| manipular objetos Python | natural | possível | exige parsing |
| operações sobre colunas | manual | natural | não é a finalidade |
| filtros/agregações tabulares | manual | natural | exige processamento |
| intercâmbio entre sistemas | Python-específico | exige serialização | muito apropriado |

## Qual é o Big-O da estrutura? {.question-slide}

<div class="fragment prompt-gold">A pergunta está mal formulada.</div>

<div class="fragment concept-definition">
Qual é a complexidade **desta operação** sobre **esta representação**?
</div>

## O repertório cresceu

| Operação / situação | Modelo |
|---|---:|
| `lista[i]` | `O(1)` |
| `append()` | `O(1)` amortizado |
| `insert(0,x)` | `O(n)` |
| `pop()` | `O(1)` |
| `pop(0)` | `O(n)` |
| operação sobre `n` valores | `O(n)` |
| ordenação eficiente | `O(n log n)` típico |
| concatenações crescentes repetidas | pode aproximar `O(n²)` |
| parsing completo de JSON | aproximadamente `O(m)` |

## O princípio da semana {.concept-slide}

<div class="concept-definition">
Não existe “o custo de uma estrutura”.
</div>

<div class="question-list">
  <div class="fragment">uma <strong>operação</strong>;</div>
  <div class="fragment">sobre uma <strong>representação</strong>;</div>
  <div class="fragment">dentro de uma <strong>sequência de operações</strong>;</div>
  <div class="fragment gold-text">para um determinado tamanho de entrada.</div>
</div>

## Voltando ao Sistema Acadêmico

<div class="question-list">
  <div class="fragment">inserir matrículas?</div>
  <div class="fragment">remover matrículas?</div>
  <div class="fragment">atualizar notas?</div>
  <div class="fragment">consultar matrícula?</div>
  <div class="fragment">ordenar rankings?</div>
  <div class="fragment">agrupar por turma?</div>
</div>

::: {.fragment .prompt-gold}
Conhecer a carga de trabalho ajuda a escolher a representação.
:::

## Um problema continua aberto {.question-slide}

Se consultar matrícula ocorrer **milhões de vezes**:

<div class="fragment question-big">ainda queremos percorrer todos os estudantes?</div>

<div class="fragment prompt-gold">
### Próxima semana
**Busca sequencial × busca binária**
</div>